apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-prod

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: namespace-config
    namespace: ssp-prod
    literals:
      - NAMESPACE_NAME=demo-prod
