apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
          env:
            - name: discovery.type
              value: "single-node"
            - name: ELASTIC_PASSWORD
              value: "password"
            - name: ELASTICSEARCH_HTTP_ENABLE
              value: "true"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
