apiVersion: apps/v1
kind: Deployment
metadata:
  name: yettel-backend
  labels:
    app: yettel-backend-label
spec:
  replicas: 1
  selector:
    matchLabels:
      service: yettel-backend
  template:
    metadata:
      labels:
        app: yettel-backend-label
        service: yettel-backend
    spec:
      initContainers:
        - name: wait-for-job
          image: bitnami/kubectl
          command:
            - "sh"
            - "-c"
            - "placeholder: while [ \"$(kubectl get job secret-manager-job -n ENV_NAME -o=jsonpath='{.status.succeeded}')\" != \"1\" ]; do\n  echo \"Waiting for pre-deploy job completion...\";\n  sleep 2;\n done"
      containers:
        - name: yettel-backend
          image: placeholder:placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          env:
            - name: spring.profiles.active
              value: native
