apiVersion: v1
kind: ConfigMap
metadata:
  name: config-files
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
    }

  logstash.yml: |
    http.host: "0.0.0.0"
    http.port: 9600
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
    log.level: info
    path.logs: /var/log/logstash
