resources:
  - ../templates/

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: secret-manager-job
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/0/volumeMounts/1/subPath",
          "value": "secret-path-prod.json"
        }
      ]
