apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yettel-prod

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: backend-config
    namespace: ssp-prod
    literals:
      - NATIVE_REFLECTION_CONFIGURATION_GENERATOR_ENABLED=false
      - SERVER_ENV=DEV
      - SERVER_PORT=8080
      - SERVER_SOCKET_FULL_HOST=wss://api-ssp-prod.balazskrizsan.com/ws
      - SERVER_SSL_ENABLED=false
      - SERVER_SSL_KEY_STORE=classpath:keystore/dev.p12
      - SITE_DOMAIN=not.yet
      - SITE_FRONTEND_HOST=https://ssp-prod.balazskrizsan.com/
      - SOCKET_IS_ENABLED_SOCKET_CONNECT_AND_DISCONNECT_LISTENERS=true
      - SOCKET_MESSAGE_BROKER_STATS_LOGGING_PERIOD_SECONDS=60
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=10
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-psql-service:47030/smartscrumpoker
