apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secret-manager
  namespace: yettel-prod
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "create", "watch", "delete", "update" ]
