apiVersion: batch/v1
kind: Job
metadata:
  name: secret-manager-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: adelchouchene/kubectl-curl
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl -L -o /usr/local/bin/sops "https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64"
              chmod +x /usr/local/bin/sops

              export GOOGLE_APPLICATION_CREDENTIALS="/google-service-account.json"

              curl -o /secret.enc.yaml $(cat /secret-path.json)

              cat <<EOF > /.sops.yaml
              creation_rules:
              - encrypted_regex: '^(data|secrets)$'
                gcp_kms: "projects/smartscrumpoker/locations/global/keyRings/sops/cryptoKeys/sops-key"
              EOF

              sops --verbose --config /.sops.yaml --decrypt /secret.enc.yaml > /secret.yaml

              kubectl apply -f /secret.yaml
          volumeMounts:
            - name: sops-secrets-volume
              mountPath: /google-service-account.json
              subPath: google-service-account.json
            - name: sops-secrets-volume
              mountPath: /secret-path.json
              subPath: placeholder
      restartPolicy: Never
      volumes:
        - name: secret-volume
          configMap:
            name: secret-configmap
        - name: sops-secrets-volume
          secret:
            secretName: sops-secrets
