apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yettel-prod

resources:
  - config/
  - ../templates/

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: yettel-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/0/image",
          "value": "kbalazsworks/yettel_backend:commit_sha_short_796e653"
        },
        {
          "op": "replace",
          "path": "/spec/template/spec/initContainers/0/command/2",
          "value": "while [ \"$(kubectl get job secret-manager-job -n yettel-prod -o=jsonpath='{.status.succeeded}')\" != \"1\" ]; do\n  echo \"Waiting for pre-deploy job completion...\";\n  sleep 2;\n done"
        }
      ]

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: yettel-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/rules/0/http/paths/0/backend/service/port/number",
          "value": 46001
        },
        {
          "op": "replace",
          "path": "/spec/rules/0/host",
          "value": "yettel-prod-api.balazskrizsan.com"
        },
        {
          "op": "replace",
          "path": "/spec/tls/0/hosts",
          "value": ["yettel-prod-api.balazskrizsan.com"]
        }
      ]
